spring:
  application:
    name: BLOG-V1
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:blog_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update